### ISSUE TITLE
no such keg

### ISSUE THREAD

**Issue by wenq1** [mulle-nat/mulle-bashfunctions#3]
Warning: mulle-kybernetik/software/mulle-bashfunctions 5.0.3 is already installed, it's just not linked.
To link this version, run:
  brew link mulle-bashfunctions
wc@wcAir MulleObjC %   brew link mulle-bashfunctions
Error: No such keg: /usr/local/Cellar/mulle-bashfunctions

**Comment by mulle-nat** [comment]
That's pretty wild (-> i have no idea, what's going wrong :)). I hope this cleans up after uninstalling and then reinstalling. If this doesn't work at all, you should have more luck with the script install.

**Comment by wenq1** [comment]
No worries. that shouldn't matter.

I'm trying to get MulleObjc module going.

**Comment by wenq1** [comment]
For the record, it is actually mine issue. Should use arm64 version of homebrew instead.
